# -*- coding: utf-8 -*-
"""belajarpython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CMNT0pphRWIXhA8e3QWCq6erZZsj32QX
"""

print("Selamat dan Semangat Irul:)")

a = 2
b = 3
c = 4
print("Hasilnya adalah= ", a,b,c)

#tipe data Boolean
print(True)

#tipe data String
print("Ayo belajar Python")
print('Belajar Python Sangat Mudah')

#tipe data Integer
print(20)

#tipe data Float
print(3.14)

#tipe data Hexadecimal
#print(9a)

#tipe data Complex
print(5j+1)

#tipe data List
print([1,2,3,4,5])
print(["satu", "dua", "tiga"])

#tipe data Tuple
print((1,2,3,4,5))
print(("satu", "dua", "tiga"))

#tipe data Dictionary
print({"nama":"Budi", 'umur':20})
#tipe data Dictionary dimasukan ke dalam variabel biodata
biodata = {"nama":"Andi", 'umur':21} #proses inisialisasi variabel biodata
print(biodata) #proses pencetakan variabel biodata yang berisi tipe data Dictionary
print(type(biodata)) #fungsi untuk mengecek jenis tipe data. akan tampil <class 'dict'> yang berarti dict adalah tipe data dictionary

frontname = "Khoirul"
lastname = "Umam"
completename = frontname + " " + lastname
NIM = 5302422030
GPA = 4.0
print("Nama Mahasiswa:", completename)
print("NIM:", NIM)
print("GPA:", GPA)
type(NIM)

#OPERATOR ARITMATIKA
""" PRIORITAS OPERASI ARITMATIKA
() --> tanda kurung
** --> eksponen atau pangkat
*, /, //, % --> perkalian pembagian
+, - --> penjumlahan pengurangan
"""
#penjumlahan (summation/addition)
print(20+17)
apel = 15
jeruk = 30
mangga = 3
buah = apel + jeruk + mangga
print("Total buah:", buah)

#pengurangan (substraction)
hutang = 500000
bayar = 250000
sisahutang = hutang-bayar
print("Sisa hutangnya adalah:", sisahutang)

#perkalian (multiplication)
hargalele = 15000
lele = 275
total = hargalele * lele
print("Total penjualan lele adalah:", total)

#pembagian (distribution)
luaspizza = 49
anak = 7
pizza_per_anak = 49/7
print("Pizza yang didapat per anak adalah:", pizza_per_anak)

#pembulatan pembagian ke bawah (floor division)
print("Hasil floor division adalah:", 21//5)

#sisabagi(remainderfor(modulus))
print("Sisa bagi 16/3 adalah:", 16%3)
#pangkat/eksponen(power of)
print("Hasil pangkatnya adalah:", 5 ** 2)

#OPERATOR PERBANDINGAN
print(5 == 5)
print(5 == 7)
print(2 != 3)
print(2 != 2)
print(7 >= 6)
print(7 >= 9)
print(5 <= 5)
print(5 <= 3)

#OPERATOR PENUGASAN
a = 10
a += 2
print(a)
a %= 5
print(a)

#IF
#Kondisi if adalah kondisi yang akan dieksekusi oleh program jika bernilai benar atau TRUE

nilai = 9

#jika kondisi benar/TRUE maka program akan mengeksekusi perintah dibawahnya
if(nilai > 7):
    print("Sembilan Lebih Besar Dari Angka Tujuh") # Kondisi Benar, Dieksekusi

#jika kondisi salah/FALSE maka program tidak akan mengeksekusi perintah dibawahnya
if(nilai > 10):
    print("Sembilan Lebih Besar Dari Angka Sepuluh") # Kondisi Salah, Maka tidak tereksekusi

num = 12
while num > 0:
  num -=3
  print(num)

#Contoh penggunaan While Loop
#Catatan: Penentuan ruang lingkup di Python bisa menggunakan tab alih-alih menggunakan tanda kurung

count = 0
while (count < 9):
  print ("The count is: ", count)
  count = count + 1

print ("Good bye!")

#Contoh pengulangan for sederhana
print("=====ANGKA=====")
angka = [1,2,3,4,5]
for x in angka:
  print(x)
print("=====BUAH=====")
#Contoh pengulangan for
buah = ["nanas", "apel", "jeruk"]
for makanan in buah:
  print ("Saya suka makan", makanan)

#NESTED LOOP
#Contoh penggunaan Nested Loop
#Catatan: Penggunaan modulo pada kondisional mengasumsikan nilai selain nol sebagai True(benar) dan nol sebagai False(salah)

i = 2;
while(i < 10):
  j = 2
  while(j <= (i/j)):
    if not(i/j): break
    j = j + 1
    if (j > i/j) : print(i, " is prime")
    i = i + 1

print("Good bye!")

print("Program Bilangan Bulat 1 hingga x")
i = 1;
x = int(input("Masukkan bilangan bulat x:"));

while i <= x:
  print(i);
  i = i + 1;

ulang = 6
for i in range (ulang):
  print(f"loop ke-{i}")

for i in range (3):
  print('Perulangan luar [i]=', i)
  for j in range (10):
    print('Perulangan dalam [i, j]=', str(i) + "," + str(j))

print("=====INI LIST=====")
my_list = [1, 'two', 3.0, [4, 5]]
print(my_list)
my_list.append(6)
print(my_list)
print(my_list[3])
print("=====INI TUPLE=====")
my_tuple = ('satu', 2.0, 3)
print(my_tuple)
#my_tuple.append(4)
print(my_tuple[1])

name = 'John Doe'
message = "John Doe belajar bahasa python di Belajarpython"
print ("name[0]: ", name[0])
print ("message[0:8: ", message[0:8])

message = 'Hello World'
print ("Updated String :- ", message[:6] + 'Python')

list = ['fisika', 'kimia', 1993, 2017]
print ("Nilai ada pada index 2 : ", list[2])

list[2] = 2001
print ("Nilai baru ada pada index 2 : ", list[2])
print(list)

len(list)
list[1]*4
2001 in list

tup = ('fisika', 'kimia', 1993, 2017)
print(tup)

# hapus tuple dengan statement del

del tup
# lalu buat kembali tuple yang baru dengan elemen yang diinginkan

tup = ('Bahasa', 'Literasi', 2020)
print("Setelah menghapus tuple :", tup)

import time; # Digunakan untuk meng-import modul time

ticks = time.time()
print ("Berjalan sejak 12:00am, January 1, 1970:", ticks) #untuk python 3 gunakan tanda kurung, print()

import time;

localtime = time.localtime(time.time())
print("Waktu lokal saat ini :", localtime)

count = 0
while count < 5:
  print(count)
  count += 1

import numpy as np
from scipy.interpolate import CubicSpline

x = [1, 2, 3, 4, 5]
y = [10, 20, 30, 40, 50]

cubic_spline_interp = CubicSpline(x, y)
new_x = 2.5
interpolated_value = cubic_spline_interp(new_x)

import random

# ===== BAGIAN 1: SETUP =====
angka_rahasia = random.randint(1, 100)
jumlah_percobaan = 0
tebakan = 0

print("Selamat datang di game Tebak Angka!")
print("Aku sudah memikirkan sebuah angka antara 1 sampai 100.")
print("Coba tebak angkanya!")

# ===== BAGIAN 2: LOOP UTAMA (diulang terus sampai tebakan benar) =====
while tebakan != angka_rahasia:
    tebakan = int(input("Tebakanmu: "))
    jumlah_percobaan += 1

    # ===== BAGIAN 3: KONDISI (IF/ELIF/ELSE) =====
    if tebakan < angka_rahasia:
        print("Terlalu rendah! Coba lagi.")
    elif tebakan > angka_rahasia:
        print("Terlalu tinggi! Coba lagi.")
    else:
        print(f"Benar! Angkanya memang {angka_rahasia}.")
        print(f"Kamu berhasil menebak dalam {jumlah_percobaan} kali percobaan!")

tinggi_badan = int(input("Berapa tinggi badanmu (cm)? "))

if tinggi_badan >= 140:
    print("Kamu boleh naik wahana ini sendirian!")
elif tinggi_badan >= 110:
    print("Kamu boleh naik, tapi harus ditemani orang dewasa.")
else:
    print("Maaf, kamu harus tumbuh lebih tinggi dulu untuk naik wahana ini.")